id = "scala"
name = "Scala"
description = "Scala support."
version = "0.1.3"
schema_version = 1
authors = [
    "Igal Tabachnik <hmemcpy@gmail.com>",
    "Jamie Thompson <bishbashboshjt@gmail.com>",
    "Michal Příhoda <michal@prihoda.net>",
]
repository = "https://github.com/scalameta/metals-zed"

[language_servers.metals]
name = "Metals (Scala Language Server)"
language = "Scala"

[grammars.scala]
repository = "https://github.com/tree-sitter/tree-sitter-scala"
commit = "d9017869dda79cefe2dc9d23c6125eda0a2d5d22"

[debug_adapters.metals-dap]
name = "Metals DAP"
schema_path = "debug_adapter_schemas/metals-dap.json"
language = "Scala"
