id = "scala"
name = "Scala"
description = "Scala support."
version = "0.2.1"
schema_version = 1
authors = [
    "Igal Tabachnik <hmemcpy@gmail.com>",
    "Jamie Thompson <bishbashboshjt@gmail.com>",
    "Michal Příhoda <michal@prihoda.net>",
]
repository = "https://github.com/scalameta/metals-zed"

[language_servers.metals]
name = "Metals (Scala Language Server)"
language = "Scala"

[grammars.scala]
repository = "https://github.com/tree-sitter/tree-sitter-scala"
commit = "97aead18d97708190a51d4f551ea9b05b60641c9"

[debug_adapters.Metals]
